#!/bin/bash
set -e
cd "$(dirname "$0")"

. setup/system.sh

which virsh > /dev/null # should fail and exit script in case of missing

LIBVIRT_VERSION=$(virsh --version)
export LIBVIRT_VERSION

if ! [ -e webapp/README.md ] || ! [ -e backend/README.md ];then
  echo "Pulling backend and webapp submodules"
  git submodule update --init --recursive
fi

ISO_DIR="$(readlink -f ~virtkick)/iso"
HDD_DIR="$(readlink -f ~virtkick)/hdd"
export ISO_DIR
export HDD_DIR

. setup/ruby.sh

. setup/node.sh

if ! [ -e node_modules/.done ];then
  rm -rf node_modules
fi

if ! [ -e node_modules ];then
  npm install
  touch node_modules/.done
fi

which pip > /dev/null || (echo "Command \"pip\" not found, please install python-pip or equivalent\"" && exit 1)

#. setup/python.sh

node starter.js "$@"

# Remember error
rc=$?
if [[ $rc != 0 ]] ; then
    exit $rc
fi
